version: "3.9"

services:
  marcador-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: marcador-sql
    environment:
      SA_PASSWORD: "Baloncesto11!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  backend:
    image: plalvarez11/marcador-baloncesto-docker:latest
    container_name: marcador-api
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__SqlServer=Server=marcador-sql,1433;Database=MarcadorDb;User Id=sa;Password=Baloncesto11!;TrustServerCertificate=True;
    depends_on:
      - marcador-sql

  frontend:
    image: plalvarez11/marcador-baloncesto-fe:latest
    container_name: marcador-api-fe
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  sql_data:
